## Data pre-processing and data manipulation

In [1]:
#import some libraries

import pandas as pd
import numpy as np

In [2]:
url = "https://bit.ly/2Qk25Xx"
df = pd.read_csv(url)
df.head(10)

C:\Users\Owner\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,173130602,12/31/2017,566,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,0,25-44,M,BLACK,1063056,207463,40.735772,-73.715638
1,173114463,12/31/2017,478,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,PL 1651503,M,Q,114,0,25-44,M,ASIAN / PACIFIC ISLANDER,1009113,219613,40.769437,-73.910241
2,173113513,12/31/2017,849,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,LOC000000V,V,K,73,1,18-24,M,BLACK,1010719,186857,40.679525,-73.904572
3,173113423,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0,25-44,M,WHITE,987831,217446,40.763523,-73.987074
4,173113421,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0,45-64,M,BLACK,987073,216078,40.759768,-73.989811
5,173130583,12/31/2017,397,"ROBBERY,UNCLASSIFIED,OPEN AREAS",105.0,ROBBERY,PL 1601001,F,K,73,0,18-24,M,BLACK,1007524,188555,40.684194,-73.916085
6,173129349,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,9,0,18-24,F,WHITE HISPANIC,990592,202391,40.722199,-73.977122
7,173128438,12/31/2017,511,"CONTROLLED SUBSTANCE, POSSESSION 7",235.0,DANGEROUS DRUGS,PL 2200300,M,M,25,0,25-44,M,BLACK,999724,230625,40.799683,-73.944112
8,173128437,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,23,2,25-44,M,BLACK HISPANIC,998165,226184,40.787496,-73.949752
9,173128433,12/31/2017,705,"FORGERY,ETC.-MISD.",358.0,OFFENSES INVOLVING FRAUD,PL 1702000,M,M,17,0,18-24,M,WHITE,991195,212559,40.750107,-73.974936

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95967 entries, 0 to 95966
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ARREST_KEY         95967 non-null  object
 1   ARREST_DATE        95873 non-null  object
 2   PD_CD              95967 non-null  int64
 3   PD_DESC            95672 non-null  object
 4   KY_CD              95672 non-null  float64
 5   OFNS_DESC          95672 non-null  object
 6   LAW_CODE           95967 non-null  object
 7   LAW_CAT_CD         95418 non-null  object
 8   ARREST_BORO        95967 non-null  object
 9   ARREST_PRECINCT    95967 non-null  int64
 10  JURISDICTION_CODE  95967 non-null  int64
 11  AGE_GROUP          95953 non-null  object
 12  PERP_SEX           95967 non-null  object
 13  PERP_RACE          95964 non-null  object
 14  X_COORD_CD         95967 non-null  int64
 15  Y_COORD_CD         95967 non-null  int64
 16  Latitude           95966 non-null  float64
 17  Longitude          95966 non-null  float64
dtypes: float64(3), int64(5), object(10)
memory usage: 13.2+ MB

In [5]:
# first approah to cleaning up our data is to remove the rows with missing values
df = df.dropna()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95011 entries, 0 to 95966
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ARREST_KEY         95011 non-null  object
 1   ARREST_DATE        95011 non-null  object
 2   PD_CD              95011 non-null  int64
 3   PD_DESC            95011 non-null  object
 4   KY_CD              95011 non-null  float64
 5   OFNS_DESC          95011 non-null  object
 6   LAW_CODE           95011 non-null  object
 7   LAW_CAT_CD         95011 non-null  object
 8   ARREST_BORO        95011 non-null  object
 9   ARREST_PRECINCT    95011 non-null  int64
 10  JURISDICTION_CODE  95011 non-null  int64
 11  AGE_GROUP          95011 non-null  object
 12  PERP_SEX           95011 non-null  object
 13  PERP_RACE          95011 non-null  object
 14  X_COORD_CD         95011 non-null  int64
 15  Y_COORD_CD         95011 non-null  int64
 16  Latitude           95011 non-null  float64
 17  Longitude          95011 non-null  float64
dtypes: float64(3), int64(5), object(10)
memory usage: 13.8+ MB

In [10]:
len(df["ARREST_KEY"].unique())

95011

In [11]:
df = df.set_index("ARREST_KEY")
df

,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
ARREST_KEY,,,,,,,,,,,,,,,,,
173130602,12/31/2017,566,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,0,25-44,M,BLACK,1063056,207463,40.735772,-73.715638
173114463,12/31/2017,478,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,PL 1651503,M,Q,114,0,25-44,M,ASIAN / PACIFIC ISLANDER,1009113,219613,40.769437,-73.910241
173113513,12/31/2017,849,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,LOC000000V,V,K,73,1,18-24,M,BLACK,1010719,186857,40.679525,-73.904572
173113423,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0,25-44,M,WHITE,987831,217446,40.763523,-73.987074
173113421,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0,45-64,M,BLACK,987073,216078,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168427638,08/24/2017,114,OBSTR BREATH/CIRCUL,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1211100,M,Q,103,0,25-44,M,ASIAN / PACIFIC ISLANDER,1041879,197084,40.707447,-73.792142
168420087,08/24/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,18-24,F,BLACK,1005346,246531,40.843329,-73.923756
168419787,08/24/2017,258,"CRIMINAL MISCHIEF 4TH, GRAFFITI",351.0,CRIMINAL MISCHIEF & RELATED OFFENSES,PL 1456002,M,M,7,0,25-44,M,BLACK,986430,199559,40.714428,-73.992138
168415098,08/24/2017,244,"BURGLARY,UNCLASSIFIED,UNKNOWN TIME",107.0,BURGLARY,PL 1402000,F,M,14,0,45-64,M,BLACK,985802,213781,40.753464,-73.994400
168415095,08/24/2017,922,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,M,30,0,45-64,M,BLACK,999458,240311,40.826269,-73.945050

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95011 entries, 173130602 to 168415095
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ARREST_DATE        95011 non-null  object
 1   PD_CD              95011 non-null  int64
 2   PD_DESC            95011 non-null  object
 3   KY_CD              95011 non-null  float64
 4   OFNS_DESC          95011 non-null  object
 5   LAW_CODE           95011 non-null  object
 6   LAW_CAT_CD         95011 non-null  object
 7   ARREST_BORO        95011 non-null  object
 8   ARREST_PRECINCT    95011 non-null  int64
 9   JURISDICTION_CODE  95011 non-null  int64
 10  AGE_GROUP          95011 non-null  object
 11  PERP_SEX           95011 non-null  object
 12  PERP_RACE          95011 non-null  object
 13  X_COORD_CD         95011 non-null  int64
 14  Y_COORD_CD         95011 non-null  int64
 15  Latitude           95011 non-null  float64
 16  Longitude          95011 non-null  float64
dtypes: float64(3), int64(5), object(9)
memory usage: 13.0+ MB

In [14]:
# we know some columns may not be useful for us, we can drop them too
dropcols = ["LAW_CODE", "ARREST_BORO", "ARREST_PRECINCT", "X_COORD_CD", "Y_COORD_CD", "Latitude",
           "Longitude"]
df = df.drop(columns=dropcols)
df

,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CAT_CD,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE
ARREST_KEY,,,,,,,,,,
173130602,12/31/2017,566,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,V,0,25-44,M,BLACK
173114463,12/31/2017,478,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,M,0,25-44,M,ASIAN / PACIFIC ISLANDER
173113513,12/31/2017,849,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,V,1,18-24,M,BLACK
173113423,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,25-44,M,WHITE
173113421,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,45-64,M,BLACK
...,...,...,...,...,...,...,...,...,...,...
168427638,08/24/2017,114,OBSTR BREATH/CIRCUL,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,25-44,M,ASIAN / PACIFIC ISLANDER
168420087,08/24/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,18-24,F,BLACK
168419787,08/24/2017,258,"CRIMINAL MISCHIEF 4TH, GRAFFITI",351.0,CRIMINAL MISCHIEF & RELATED OFFENSES,M,0,25-44,M,BLACK
168415098,08/24/2017,244,"BURGLARY,UNCLASSIFIED,UNKNOWN TIME",107.0,BURGLARY,F,0,45-64,M,BLACK
168415095,08/24/2017,922,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,M,0,45-64,M,BLACK

### Create new columns
inside LAW_CAT_CD
> F is for felony - 36 months of jail time
>
> M is for misdemeanors - 12 months of jail time
>
> V is for violation - 1 month of jail time

In [18]:
#numpy - an explainer
np.where(1>2, "apple", 
         np.where(3>2, "watermelon", "pear") #this is in the else clause
        )

array('watermelon', dtype='<U10')

In [19]:
df["JAIL_TIME"] = np.where(df["LAW_CAT_CD"] == "F", 36, 
         np.where(df["LAW_CAT_CD"] == "M", 12, 1)
        )

In [20]:
df.head()

,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CAT_CD,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,JAIL_TIME
ARREST_KEY,,,,,,,,,,,
173130602,12/31/2017,566,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,V,0,25-44,M,BLACK,1
173114463,12/31/2017,478,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,M,0,25-44,M,ASIAN / PACIFIC ISLANDER,12
173113513,12/31/2017,849,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,V,1,18-24,M,BLACK,1
173113423,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,25-44,M,WHITE,12
173113421,12/31/2017,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,M,0,45-64,M,BLACK,12

#### this idea of creating new columns has a name - Feature Engineering!

## Clean data when dealing with missing numerical data!

In [21]:
data = pd.Series([1,np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [22]:
#filter our our data
data[data.isnull()]# isnull a function that detects for us null

1     NaN
3    None
dtype: object

In [24]:
data[data.notnull()]# notnull a function that detects for us notnull

0        1
2    hello
dtype: object

### Dropna is a really destructive technique, we can potentially lose alot of data when we use drop na!

In [25]:
#create a small data
ndata = pd.Series([np.nan, np.nan, 3, None, 2])
ndata

0    NaN
1    NaN
2    3.0
3    NaN
4    2.0
dtype: float64

In [28]:
#method 1: is to fill using a specific number
#typical way is to fillm NaN with the number 0, we can use a meaningful number such as the
#mean, or the median
nmean = ndata.mean()
ndata.fillna(nmean) #fill with the mean

0    2.5
1    2.5
2    3.0
3    2.5
4    2.0
dtype: float64

In [29]:
ndata.fillna(0)

0    0.0
1    0.0
2    3.0
3    0.0
4    2.0
dtype: float64

In [34]:
ndata

0    NaN
1    NaN
2    3.0
3    NaN
4    2.0
dtype: float64

In [31]:
#method 2: forward fill
ndata.fillna(method="ffill")

0    NaN
1    NaN
2    3.0
3    3.0
4    2.0
dtype: float64

In [32]:
ndata.fillna?

In [33]:
#method 3: backfill
ndata.fillna(method="bfill")

0    3.0
1    3.0
2    3.0
3    2.0
4    2.0
dtype: float64