### Working with pandas

In [1]:
#import our libraries

import pandas as pd
import numpy as np

In [2]:
#data structures

#1D data structure - SERIES
#2D data structure - DATAFRAME

s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
s[2]

3

In [4]:
s2 = pd.Series([1,2,3,4], index=["a","b","c","d"])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
#our 1d data series can be created using a dictionary - Key and Value pair
pop_dict = {"Singapore": 5.7,
           "Indonesia": 270.8,
           "Italy" : 45.3,
           "UK" : 30.1}

pop_series = pd.Series(pop_dict)
pop_series

Singapore      5.7
Indonesia    270.8
Italy         45.3
UK            30.1
dtype: float64

In [6]:
#how can i extract out the population of italy?
pop_series['Italy']

45.3

In [7]:
#dataframes - its multi dimensional data structure
data = {'country': ['Singapore', 'France', 'Germany'],
        'population': [5.5, 64, 82],'area': [31000, 672000, 360000],
        'capital': ['Singapore', 'Paris', 'Berlin']}

#convert into a dataframe
countrydf = pd.DataFrame(data)
countrydf

     country  population    area    capital
0  Singapore         5.5   31000  Singapore
1     France        64.0  672000      Paris
2    Germany        82.0  360000     Berlin

In [8]:
 countrydf["area"] # can you tell me what data structure is this?

0     31000
1    672000
2    360000
Name: area, dtype: int64

In [9]:
type(countrydf["area"])

pandas.core.series.Series

In [10]:
 countrydf["area"][1] #this is the area of france

672000

In [11]:
# we can perform operations on panda dataframes
#From the country perspective, we want find the population density of every country
#population / area
countrydf["population"] / countrydf["area"]

0    0.000177
1    0.000095
2    0.000228
dtype: float64

In [13]:
#min or max of any column
#countrydf["area"].min()
countrydf["area"].max()

672000

In [ ]:
countrydf = countrydf.set_index("country")
countrydf

In [17]:
countrydf

           population    area    capital
country
Singapore         5.5   31000  Singapore
France           64.0  672000      Paris
Germany          82.0  360000     Berlin

In [15]:
countrydf["area"]["France"]

672000

In [21]:
# we want to sort on area
countrydf.sort_values('area', ascending=True)

           population    area    capital
country
Singapore         5.5   31000  Singapore
Germany          82.0  360000     Berlin
France           64.0  672000      Paris

In [22]:
#very useful function - this gives us a basic statistical output for numerical columns
countrydf.describe()

       population           area
count    3.000000       3.000000
mean    50.500000  354333.333333
std     39.996875  320537.569301
min      5.500000   31000.000000
25%     34.750000  195500.000000
50%     64.000000  360000.000000
75%     73.000000  516000.000000
max     82.000000  672000.000000

## INDEXING AND SLICING DATA

#### Indexing - Being able to access different parts of the data using rows and columns index
#### Slicing - Being able to extract a subset of data using index of rows/columns

In [23]:
countrydf

           population    area    capital
country
Singapore         5.5   31000  Singapore
France           64.0  672000      Paris
Germany          82.0  360000     Berlin

In [25]:
# i want the areas and population of singapore and france
#loc - row locations and column column locations
countrydf.loc['Singapore':"France", 'population':'area']#row, col

           population    area
country
Singapore         5.5   31000
France           64.0  672000

In [27]:
#sau we want populatioon and capital
popcap = ['population','capital']
countrydf.loc['Singapore':"France", popcap]#row, col

           population    capital
country
Singapore         5.5  Singapore
France           64.0      Paris

In [28]:
countrydf.loc['Singapore':"France", popcap].describe()

       population
count    2.000000
mean    34.750000
std     41.365747
min      5.500000
25%     20.125000
50%     34.750000
75%     49.375000
max     64.000000

## Filtering - We want to subset our data - where area of the country is more than 100000

In [31]:
mask = countrydf["area"] > 100000
countrydf[mask] # this is filtering

         population    area capital
country
France         64.0  672000   Paris
Germany        82.0  360000  Berlin

In [32]:
mask

country
Singapore    False
France        True
Germany       True
Name: area, dtype: bool

### Using index - iloc to manipulate our data

In [33]:
#dataframes - its multi dimensional data structure
data = {'country': ['Singapore', 'France', 'Germany'],
        'population': [5.5, 64, 82],'area': [31000, 672000, 360000],
        'capital': ['Singapore', 'Paris', 'Berlin']}

#convert into a dataframe
countrydf = pd.DataFrame(data)
countrydf

     country  population    area    capital
0  Singapore         5.5   31000  Singapore
1     France        64.0  672000      Paris
2    Germany        82.0  360000     Berlin

In [34]:
## simulate this  - countrydf.loc['Singapore':"France", 'population':'area']#row, col
countrydf.iloc[0:2, 1:3] #row, col

   population    area
0         5.5   31000
1        64.0  672000

#### Say we got the area of singapore wrong, we can change the area using the following:

In [36]:
countrydf.iloc[0, 2] = 40000
countrydf

     country  population    area    capital
0  Singapore         5.5   40000  Singapore
1     France        64.0  672000      Paris
2    Germany        82.0  360000     Berlin

In [37]:
## when we created the population density pandas series we can also similarly create a column
#From the country perspective, we want find the population density of every country
#population / area
countrydf['popdensity'] = countrydf["population"] / countrydf["area"]
countrydf

     country  population    area    capital  popdensity
0  Singapore         5.5   40000  Singapore    0.000138
1     France        64.0  672000      Paris    0.000095
2    Germany        82.0  360000     Berlin    0.000228

In [39]:
#rename the column
countrydf = countrydf.rename(columns={'popdensity':'population_density'})
countrydf

     country  population    area    capital  population_density
0  Singapore         5.5   40000  Singapore            0.000138
1     France        64.0  672000      Paris            0.000095
2    Germany        82.0  360000     Berlin            0.000228

### end of working with pandas